// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("answers")]
    [Index(nameof(OrganizationId), Name = "Answers_fk1")]
    [Index(nameof(ApplicationId), Name = "ApplicationId", IsUnique = true)]
    [Index(nameof(AttachmentId), Name = "AttachmentId", IsUnique = true)]
    public partial class Answer
    {
        [Key]
        [Column(TypeName = "int(11)")]
        public int Id { get; set; }
        [StringLength(255)]
        public string ResponsiblePerson { get; set; } = null!;
        [StringLength(255)]
        public string Executor { get; set; } = null!;
        [StringLength(255)]
        public string RerponseLetter { get; set; } = null!;
        [Column(TypeName = "int(11)")]
        public int AttachmentId { get; set; }
        [Column(TypeName = "int(11)")]
        public int RegisterNumber { get; set; }
        [StringLength(255)]
        public string Author { get; set; } = null!;
        [StringLength(255)]
        public string Result { get; set; } = null!;
        [Column(TypeName = "text")]
        public string Conclusion { get; set; } = null!;
        [Column(TypeName = "int(11)")]
        public int OrganizationId { get; set; }
        [Column(TypeName = "int(11)")]
        public int ApplicationId { get; set; }

        [ForeignKey(nameof(ApplicationId))]
        [InverseProperty("Answer")]
        public virtual Application Application { get; set; } = null!;
        [ForeignKey(nameof(AttachmentId))]
        [InverseProperty("Answer")]
        public virtual Attachment Attachment { get; set; } = null!;
        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty(nameof(User.Answers))]
        public virtual User Organization { get; set; } = null!;

        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
}