// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("answers")]
    [Index(nameof(AuthorId), Name = "Answers_fk1")]
    [Index(nameof(ApplicationId), Name = "ApplicationId", IsUnique = true)]
    [Index(nameof(AttachmentId), Name = "AttachmentId", IsUnique = true)]
    public partial class Answer : BaseModel
    {
        [Key]
        [Column(TypeName = "int(11)")]
        public int Id { get; set; }
        [StringLength(255)]
        [Display(Name = "Ответственное лицо")]
        public string ResponsiblePerson { get; set; } = null!;
        [StringLength(255)]
        [Display(Name = "Исполнитель")]
        public string Executor { get; set; } = null!;
        [Column(TypeName = "text")]
        [Display(Name = "Ответное письмо")]
        public string ResponseLetter { get; set; } = null!;
        [Column(TypeName = "int(11)")]
        [Display(Name = "Вложение")]
        public int? AttachmentId { get; set; }
        [Column(TypeName = "int(11)")]
        [Display(Name = "Регистрационный номер")]
        public int RegisterNumber { get; set; }
        [StringLength(255)]
        [Display(Name = "Результат рассмотрения")]
        public string Result { get; set; } = null!;
        [Column(TypeName = "text")]
        [Display(Name = "Вывод ")]
        public string Conclusion { get; set; } = null!;
        [Column(TypeName = "int(11)")]
        [Display(Name = "Организация")]
        public int AuthorId { get; set; }
        [Column(TypeName = "int(11)")]
        [Display(Name = "Заявление")]
        public int ApplicationId { get; set; }

        [ForeignKey(nameof(ApplicationId))]
        [InverseProperty("Answer")]
        public virtual Application Application { get; set; } = null!;
        [Display(Name = "Вложение")]
        [ForeignKey(nameof(AttachmentId))]
        [InverseProperty("Answer")]
        public virtual Attachment? Attachment { get; set; } = null!;
        [Display(Name = "Организация")]
        [ForeignKey(nameof(AuthorId))]
        [InverseProperty(nameof(User.Answers))]
        public virtual User Author { get; set; } = null!;

    }
}