// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CallCenterCRM.Utilities;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("application")]
    [Index(nameof(ClassificationId), Name = "Application_fk0")]
    [Index(nameof(RecipientId), Name = "Application_fk1")]
    [Index(nameof(ApplicantId), Name = "Application_fk3")]
    [Index(nameof(AttachmentId), Name = "AttachmentId", IsUnique = true)]
    public partial class Application : BaseModel
    {
        public Application()
        {
            TypesList = new List<SelectListItem>();
            StatusList = new List<SelectListItem>();

            TypesList = ListEnums.GetEnumList<AppTypes>(TypesList);
            StatusList = ListEnums.GetEnumList<ApplicationStatus>(StatusList);
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int Id { get; set; }
        
        [Column(TypeName = "int(11)")]
        [Display(Name = "Классификация")]
        public int ClassificationId { get; set; }
        [Column(TypeName = "datetime")]
        [Display(Name = "Срок")]
        public DateTime ExpireTime { get; set; }
        
        [Display(Name = "Тип обращения")]
        public AppTypes Type { get; set; }
        [Column(TypeName = "text")]
        [Display(Name = "Комментарий")]
        public string? Comment { get; set; } = null!;
        [Column(TypeName = "text")]
        [Display(Name = "Причина")]
        public string? Reason { get; set; } = null!;
        [Display(Name = "Избранный")]
        public bool IsSelected { get; set; }
        [Column(TypeName = "int(11)")]
        [Display(Name = "Получатель")]
        public int RecipientId { get; set; }
        [Column(TypeName = "int(11)")]
        [Display(Name = "Вложение ")]
        public int? AttachmentId { get; set; }
        [Display(Name = "Заявител")]
        [Column(TypeName = "int(11)")]
        public int ApplicantId { get; set; }
        [Display(Name = "Статус")]
        public ApplicationStatus Status { get; set; }
        [Display(Name = "Заявител")]
        [ForeignKey(nameof(ApplicantId))]
        [InverseProperty("Applications")]
        public virtual Applicant? Applicant { get; set; } = null!;
        [Display(Name = "Вложение ")]
        [ForeignKey(nameof(AttachmentId))]
        [InverseProperty("Application")]
        public virtual Attachment? Attachment { get; set; } = null!;
        [Display(Name = "Классификация")]
        [ForeignKey(nameof(ClassificationId))]
        [InverseProperty("Applications")]
        public virtual Classification? Classification { get; set; } = null!;
        [Display(Name = "Получатель")]
        [ForeignKey(nameof(RecipientId))]
        [InverseProperty("Applications")]
        public virtual User? Recipient { get; set; } = null!;
        [InverseProperty("Application")]
        public virtual Answer? Answer { get; set; } = null!;


        //[StringLength(255)]
        //[Display(Name = "Соответствующие обращения")]
        //public string? RelevantApplications { get; set; } = null!;

        /*notmapped*/
        [NotMapped]
        public List<SelectListItem> TypesList { get; set; }
        [NotMapped]
        public List<SelectListItem> StatusList { get; set; }

        /* / notmapped*/
    }
}