// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("attachments")]
    public partial class Attachment
    {
        [Key]
        [Column(TypeName = "int(11)")]
        public int Id { get; set; }
        [Column(TypeName = "int(11)")]
        public int Type { get; set; }
        [StringLength(255)]
        public string HashName { get; set; } = null!;
        [StringLength(255)]
        public string Path { get; set; } = null!;
        [StringLength(255)]
        public string OriginName { get; set; } = null!;
        [StringLength(255)]
        public string Extension { get; set; } = null!;

        [InverseProperty("Attachment")]
        public virtual Answer Answer { get; set; } = null!;
        [InverseProperty("Attachment")]
        public virtual Application Application { get; set; } = null!;

        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
}