// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("attachments")]
    public partial class Attachment : BaseModel
    {
        [Key]
        [Column(TypeName = "int(11)")]
        public int Id { get; set; }
        [Column(TypeName = "int(11)")]
        [Display(Name = "Тип")]
        public int Type { get; set; }
        [StringLength(255)]
        [Display(Name = "Имя хеша")]
        public string HashName { get; set; } = null!;
        [StringLength(255)]
        [Display(Name = "Путь")]
        public string Path { get; set; } = null!;
        [StringLength(255)]
        [Display(Name = "Оригинальное название")]
        public string OriginName { get; set; } = null!;
        [StringLength(255)]
        [Display(Name = "Расширение")]
        public string Extension { get; set; } = null!;
        [InverseProperty("Attachment")]
        public virtual Answer? Answer { get; set; }
        [InverseProperty("Attachment")]
        public virtual Application? Application { get; set; }
    }
}