// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CallCenterCRM.Utilities;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("citydistrict")]
    public partial class Citydistrict : BaseModel
    {
        public Citydistrict()
        {
            Applicants = new HashSet<Applicant>();

            RegionsList = new List<SelectListItem>();

            RegionsList = ListEnums.GetEnumList<Regions>(RegionsList);
        }

        [Key]
        public int Id { get; set; }
        [StringLength(255)]
        [Display(Name = "Название")]
        public string Title { get; set; } = null!;
        [Display(Name = "Регион")]
        public Regions Region { get; set; }
        
        [InverseProperty(nameof(Applicant.CityDistrict))]
        public virtual ICollection<Applicant> Applicants { get; set; }

        [NotMapped]
        public List<SelectListItem> RegionsList { get; set; }
    }
}