// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("citydistrict")]
    public partial class Citydistrict
    {
        public Citydistrict()
        {
            Applicants = new HashSet<Applicant>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int Id { get; set; }
        [StringLength(255)]
        public string Title { get; set; } = null!;
        [Column(TypeName = "int(11)")]
        public int RegionId { get; set; }

        [InverseProperty(nameof(Applicant.CityDistrict))]
        public virtual ICollection<Applicant> Applicants { get; set; }

        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
}