// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("classification")]
    public partial class Classification : BaseModel
    {
        public Classification()
        {
            Applications = new HashSet<Application>();
            Users = new HashSet<User>();
        }

        [Key]
        public int Id { get; set; }

        [StringLength(255)]
        [Display(Name = "Название")]
        public string Title { get; set; } = null!;

        [StringLength(255)]
        [Display(Name = "Направление")]
        public string Direction { get; set; }= null!;

        [StringLength(255)]
        [Display(Name = "Значение")]
        public string Value { get; set; } = null!;

        [Display(Name = "Актив")]
        public bool IsActive { get; set; }

        [Display(Name = "Описание")]
        public string? Description { get; set; }

        [InverseProperty(nameof(Application.Classification))]
        public virtual ICollection<Application> Applications { get; set; }

        [InverseProperty(nameof(User.Classification))]
        public virtual ICollection<User> Users { get; set; }
    }
}