// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("classification")]
    [Index(nameof(DirectionId), Name = "Classification_fk0")]

    public partial class Classification : BaseModel
    {
        public Classification()
        {
            Applications = new HashSet<Application>();
        }

        [Key]
        public int Id { get; set; }

        [StringLength(255)]
        [Display(Name = "Название")]
        public string Title { get; set; } = null!;

        [Display(Name = "Актив")]
        public bool IsActive { get; set; }

        [Display(Name = "Описание")]
        public string? Description { get; set; }

        [Display(Name = "Направление")]
        public int? DirectionId { get; set; }

        [Display(Name = "Направление")]
        [ForeignKey(nameof(DirectionId))]
        [InverseProperty("Classifications")]
        public virtual Direction? Direction { get; set; } = null!;

        [InverseProperty(nameof(Application.Classification))]
        public virtual ICollection<Application> Applications { get; set; }
    }
}