// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("classification")]
    public partial class Classification : BaseModel
    {
        public Classification()
        {
            Applications = new HashSet<Application>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int Id { get; set; }
        [StringLength(255)]
        public string Title { get; set; } = null!;
        [Column(TypeName = "text")]
        public string? Description { get; set; }
        [StringLength(255)]
        public string Direction { get; set; } = null!;
        [StringLength(255)]
        public string Value { get; set; } = null!;

        [InverseProperty(nameof(Application.Classification))]
        public virtual ICollection<Application> Applications { get; set; }
    }
}