// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("direction")]
    public partial class Direction : BaseModel
    {
        public Direction()
        {
            Classifications = new HashSet<Classification>();
            Users = new HashSet<User>();
        }

        [Key]
        public int Id { get; set; }

        [StringLength(255)]
        [Display(Name = "Название")]
        public string Title { get; set; } = null!;

        [StringLength(255)]
        [Display(Name = "Значение")]
        public string? Consequence { get; set; } = null!;

        [Display(Name = "Описание")]
        public string? Description { get; set; }

        [InverseProperty(nameof(Classification.Direction))]
        public virtual ICollection<Classification> Classifications { get; set; }

        [InverseProperty(nameof(User.Direction))]
        public virtual ICollection<User> Users { get; set; }
    }
}