// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CallCenterCRM.Models
{
    [Table("users")]
    [Index(nameof(Email), Name = "Email", IsUnique = true)]
    [Index(nameof(Username), Name = "Username", IsUnique = true)]
    [Index(nameof(OrganizationId), Name = "Users_fk0")]
    public partial class User
    {
        public User()
        {
            Answers = new HashSet<Answer>();
            Applicants = new HashSet<Applicant>();
            Applications = new HashSet<Application>();
            InverseOrganization = new HashSet<User>();
        }

        [Key]
        [Column(TypeName = "int(11)")]
        public int Id { get; set; }
        public string? Email { get; set; }
        [StringLength(255)]
        public string City { get; set; } = null!;
        [StringLength(255)]
        public string Contact { get; set; } = null!;
        public string Username { get; set; } = null!;
        [StringLength(255)]
        public string Password { get; set; } = null!;
        [StringLength(255)]
        public string? OrganizationName { get; set; }
        [Column(TypeName = "int(11)")]
        public int? OrganizationId { get; set; }
        [StringLength(255)]
        public string? Surname { get; set; }
        [StringLength(255)]
        public string? Firstname { get; set; }
        [StringLength(255)]
        public string? Middlename { get; set; }
        [Column(TypeName = "text")]
        public string? PasswordData { get; set; }
        [Column(TypeName = "text")]
        public string? Address { get; set; }
        [StringLength(255)]
        public string? Type { get; set; }

        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty(nameof(User.InverseOrganization))]
        public virtual User? Organization { get; set; }
        [InverseProperty(nameof(Answer.Organization))]
        public virtual ICollection<Answer> Answers { get; set; }
        [InverseProperty(nameof(Applicant.Organization))]
        public virtual ICollection<Applicant> Applicants { get; set; }
        [InverseProperty(nameof(Application.User))]
        public virtual ICollection<Application> Applications { get; set; }
        [InverseProperty(nameof(User.Organization))]
        public virtual ICollection<User> InverseOrganization { get; set; }

        public DateTime CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
}