stages:
  - build
build:
  stage: build
  only:
  - master
  script:
  - cd CallCenterCRM/
  - dotnet restore
  - service crm stop
  - dotnet publish --no-restore -c Release ./ --output /var/www/call-center-crm/
  - service crm start