// <auto-generated />
using System;
using CallCenterCRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CallCenterCRM.Migrations
{
    [DbContext(typeof(CallcentercrmContext))]
    [Migration("20220221102442_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("CallCenterCRM.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("AttachmentId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Executor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int(11)");

                    b.Property<int>("RegisterNumber")
                        .HasColumnType("int(11)");

                    b.Property<string>("ResponseLetter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsiblePerson")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OrganizationId" }, "Answers_fk1");

                    b.HasIndex(new[] { "ApplicationId" }, "ApplicationId")
                        .IsUnique();

                    b.HasIndex(new[] { "AttachmentId" }, "AttachmentId")
                        .IsUnique();

                    b.ToTable("answers");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("AdditionalNote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 2, 21, 15, 24, 42, 308, DateTimeKind.Local).AddTicks(5883));

                    b.Property<int?>("CityDistrictId")
                        .HasColumnType("int(11)");

                    b.Property<bool>("Confidentiality")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Employment")
                        .HasColumnType("int");

                    b.Property<string>("ExtraContact")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Maxalla")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MeaningOfApplication")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Middlename")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int(11)");

                    b.Property<int>("ReferenceSource")
                        .HasColumnType("int");

                    b.Property<int>("Region")
                        .HasColumnType("int(11)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CityDistrictId" }, "Applicants_fk0");

                    b.HasIndex(new[] { "OrganizationId" }, "Applicants_fk1");

                    b.ToTable("applicants");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int(11)");

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int(11)");

                    b.Property<int>("ClassificationId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RelevantApplications")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int(11)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClassificationId" }, "Application_fk0");

                    b.HasIndex(new[] { "UserId" }, "Application_fk1");

                    b.HasIndex(new[] { "ApplicantId" }, "Application_fk3");

                    b.HasIndex(new[] { "AttachmentId" }, "AttachmentId")
                        .IsUnique()
                        .HasDatabaseName("AttachmentId1");

                    b.ToTable("application");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HashName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OriginName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int(11)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("attachments");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Citydistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("citydistrict");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("classification");
                });

            modelBuilder.Entity("CallCenterCRM.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Firstname")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Middlename")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int(11)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordData")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Surname")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "Username")
                        .IsUnique();

                    b.HasIndex(new[] { "OrganizationId" }, "Users_fk0");

                    b.ToTable("users");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Answer", b =>
                {
                    b.HasOne("CallCenterCRM.Models.Application", "Application")
                        .WithOne("Answer")
                        .HasForeignKey("CallCenterCRM.Models.Answer", "ApplicationId")
                        .IsRequired()
                        .HasConstraintName("Answers_fk2");

                    b.HasOne("CallCenterCRM.Models.Attachment", "Attachment")
                        .WithOne("Answer")
                        .HasForeignKey("CallCenterCRM.Models.Answer", "AttachmentId")
                        .HasConstraintName("Answers_fk0");

                    b.HasOne("CallCenterCRM.Models.User", "Organization")
                        .WithMany("Answers")
                        .HasForeignKey("OrganizationId")
                        .IsRequired()
                        .HasConstraintName("Answers_fk1");

                    b.Navigation("Application");

                    b.Navigation("Attachment");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Applicant", b =>
                {
                    b.HasOne("CallCenterCRM.Models.Citydistrict", "CityDistrict")
                        .WithMany("Applicants")
                        .HasForeignKey("CityDistrictId")
                        .HasConstraintName("Applicants_fk0");

                    b.HasOne("CallCenterCRM.Models.User", "Organization")
                        .WithMany("Applicants")
                        .HasForeignKey("OrganizationId")
                        .HasConstraintName("Applicants_fk1");

                    b.Navigation("CityDistrict");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Application", b =>
                {
                    b.HasOne("CallCenterCRM.Models.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .IsRequired()
                        .HasConstraintName("Application_fk3");

                    b.HasOne("CallCenterCRM.Models.Attachment", "Attachment")
                        .WithOne("Application")
                        .HasForeignKey("CallCenterCRM.Models.Application", "AttachmentId")
                        .IsRequired()
                        .HasConstraintName("Application_fk2");

                    b.HasOne("CallCenterCRM.Models.Classification", "Classification")
                        .WithMany("Applications")
                        .HasForeignKey("ClassificationId")
                        .IsRequired()
                        .HasConstraintName("Application_fk0");

                    b.HasOne("CallCenterCRM.Models.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Application_fk1");

                    b.Navigation("Applicant");

                    b.Navigation("Attachment");

                    b.Navigation("Classification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CallCenterCRM.Models.User", b =>
                {
                    b.HasOne("CallCenterCRM.Models.User", "Organization")
                        .WithMany("InverseOrganization")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Applicant", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Application", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();
                });

            modelBuilder.Entity("CallCenterCRM.Models.Attachment", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();

                    b.Navigation("Application")
                        .IsRequired();
                });

            modelBuilder.Entity("CallCenterCRM.Models.Citydistrict", b =>
                {
                    b.Navigation("Applicants");
                });

            modelBuilder.Entity("CallCenterCRM.Models.Classification", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("CallCenterCRM.Models.User", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Applicants");

                    b.Navigation("Applications");

                    b.Navigation("InverseOrganization");
                });
#pragma warning restore 612, 618
        }
    }
}
